# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layerWithForm2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(614, 429)
        self.computerNumber = QtWidgets.QLabel(OtherWindow)
        self.computerNumber.setGeometry(QtCore.QRect(40, 50, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.computerNumber.setFont(font)
        self.computerNumber.setObjectName("computerNumber")
        self.label_2 = QtWidgets.QLabel(OtherWindow)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(OtherWindow)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(OtherWindow)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(OtherWindow)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.nextBtn = QtWidgets.QPushButton(OtherWindow)
        self.nextBtn.setGeometry(QtCore.QRect(440, 370, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.ip = QtWidgets.QLineEdit(OtherWindow)
        self.ip.setGeometry(QtCore.QRect(220, 130, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ip.setFont(font)
        self.ip.setObjectName("ip")
        self.port = QtWidgets.QLineEdit(OtherWindow)
        self.port.setGeometry(QtCore.QRect(220, 190, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.port.setFont(font)
        self.port.setObjectName("port")
        self.login = QtWidgets.QLineEdit(OtherWindow)
        self.login.setGeometry(QtCore.QRect(220, 250, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(OtherWindow)
        self.password.setGeometry(QtCore.QRect(220, 310, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setReadOnly(False)
        self.password.setObjectName("password")
        self.prevBtn = QtWidgets.QPushButton(OtherWindow)
        self.prevBtn.setGeometry(QtCore.QRect(10, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.prevBtn.setFont(font)
        self.prevBtn.setObjectName("prevBtn")
        self.statusBtn = QtWidgets.QPushButton(OtherWindow)
        self.statusBtn.setGeometry(QtCore.QRect(300, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusBtn.setFont(font)
        self.statusBtn.setObjectName("statusBtn")
        self.status = QtWidgets.QLabel(OtherWindow)
        self.status.setGeometry(QtCore.QRect(450, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.status.setFont(font)
        self.status.setObjectName("status")

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "Form"))
        self.computerNumber.setText(_translate("OtherWindow", "Computer #n"))
        self.label_2.setText(_translate("OtherWindow", "IP"))
        self.label_3.setText(_translate("OtherWindow", "Port"))
        self.label_4.setText(_translate("OtherWindow", "Login"))
        self.label_5.setText(_translate("OtherWindow", "Password"))
        self.nextBtn.setText(_translate("OtherWindow", "Next Workspace"))
        self.ip.setText(_translate("OtherWindow", "192.168.30.144"))
        self.port.setText(_translate("OtherWindow", "80"))
        self.login.setText(_translate("OtherWindow", "192.168.30.144"))
        self.password.setText(_translate("OtherWindow", "192.168.30.144"))
        self.prevBtn.setText(_translate("OtherWindow", "Previous Workspace"))
        self.statusBtn.setText(_translate("OtherWindow", "Check status "))
        self.status.setText(_translate("OtherWindow", "Status : "))
